### ISSUE TITLE
[BUG] Validation function for symmetrical calculations also checks asymmetrical attributes 

### ISSUE THREAD

**Issue by bramstoeller** [PowerGridModel/power-grid-model#161]
When running `validate_input_data`, there is an argument `symmetric` (which is False by default). The results is that NaN values are allowed for attributes that are used for symmetrical calculations, like zero-sequence serial resistance `r0`. But if these fields contain invalid values (like `r0 == x0 == 0`), the validation still fails.

Suggested solution: Ignore these checks for symmetrical calculations.

**Comment by TonyXiang8787** [comment]
During a discussion it is decided that this should be the preferred behavior. If an attribute is provided, it should be within the allowed range all the time.
