### ISSUE TITLE
[BUG] Program will crash if you have NaN in the input, but valid data in batch set

### ISSUE THREAD

**Issue by TonyXiang8787** [PowerGridModel/power-grid-model#193]
Approach:

Add default value in the `preapre_power_flow_input` and `prepare_state_estimation_input` function for all inputs vector.

https://github.com/PowerGridModel/power-grid-model/blob/9d9fa4e6348b2ea3d42ab6ea93eb220d89eb1b07/power_grid_model_c/power_grid_model/include/power_grid_model/main_model.hpp#L1182

https://github.com/PowerGridModel/power-grid-model/blob/9d9fa4e6348b2ea3d42ab6ea93eb220d89eb1b07/power_grid_model_c/power_grid_model/include/power_grid_model/main_model.hpp#L1199

# Default values for Power Flow

`s_injection`: `ComplexValue<sym>{1.0}`
`source`: `ComplexValue<sym>{1.0}`

# Default values for State Estimation

`shunt_status`: `0`
`load_gen_status`: `0`
`measured_voltage`: `{ ComplexValue<sym>{1.0}, 1.0 }`
`measured_*_power`: `{ ComplexValue<sym>{0.0}, 1.0 }`
`measured_bus_injection`: `{ ComplexValue<sym>{0.0}, 1.0 }`

## source status

```
se_input[i].source_status.resize(math_topology_[i]->n_source());
se_input[i].source_status[math_topology_[i]->slack_bus_] = ComplexValue<sym>{1.0};

```

# Batch calculation

When you (indirectly) call `prepare_*_input` in the topology caching step in batch calculation, skip the retrieval of the real values, only use the default values.

**Comment by mgovers** [comment]
@TonyXiang8787 isn't this enough to just fix everything?

```cpp
        // calculate once to cache topology, ignore results, all math solvers are initialized
        (this->*calculation_fn)(std::numeric_limits<double>::infinity(), 0, calculation_method);
```

**Comment by mgovers** [comment]
> @TonyXiang8787 isn't this enough to just fix everything?
> 
> ```c++
>         // calculate once to cache topology, ignore results, all math solvers are initialized
>         (this->*calculation_fn)(std::numeric_limits<double>::infinity(), 0, calculation_method);
> ```

After discussion: this does not suffice. There are direct calculation methods that do not use tolerance and iterations
