### ISSUE TITLE
[FEATURE] make the line input parameter i_n as optional, and default to e.g. np.nan

### ISSUE THREAD

**Issue by leiwu84** [PowerGridModel/power-grid-model#253]
The input parameter `i_n` is not a must-have value to enable a power-flow calculation. It is rather a reference value to determine the loading percentage of a line. Sometimes users do not have the rated current value but still need to run power flow. Thus, I suggest making it optional. For example default as `np.nan`. If users do not provide this argument, the resulting loading percentage is then <some_value> / np.nan * 100 = np.nan.

**Comment by TonyXiang8787** [comment]
TODO

- Label `i_n` as optional in the data validation script in Python
- Change the component documentation
- Add new validation test dataset with `i_n` not provied.
