### ISSUE TITLE
[FEATURE] Create COMMITTERS.md

### ISSUE THREAD

**Issue by Jonasvdbo** [PowerGridModel/power-grid-model#422]
For the Power Grid Model to be ready to move from Sandbox stage to Incubation stage, it needs to have a COMMITTERS.md file to define individuals or teams that are responsible for code in a repository; document current project owners and current and emeritus committers. 

For more information see: https://wiki.lfenergy.org/display/HOME/Technical+Project+Lifecycle

**Comment by TonyXiang8787** [comment]
Fixed in https://github.com/PowerGridModel/.github/pull/11
