### ISSUE TITLE
Add type hinting to Python API

### ISSUE THREAD

**Issue by mgovers** [PowerGridModel/power-grid-model#465]
See the TODO in https://github.com/PowerGridModel/power-grid-model/blob/81b1f8c900152fd32ce64e86cb3fb0edb4f2b7d7/src/power_grid_model/data_types.py#L13

Support for Python 3.8 was dropped in #464

**Comment by Cbit11** [comment]
I'll do it

**Comment by mgovers** [comment]
Awesome! LMK if you need any help

**Comment by mgovers** [comment]
@Cbit11 how is it going with the development?

**Comment by Jerry-Jinfeng-Guo** [comment]
I don't understand this issue yet, what's wrong with this [data_types.py](https://github.com/PowerGridModel/power-grid-model/blob/81b1f8c900152fd32ce64e86cb3fb0edb4f2b7d7/src/power_grid_model/data_types.py#L13) document?

**Comment by mgovers** [comment]
> this may already be done in #613 and #648

this is actually not entirely true.

* Starting python3.9, we have `list[Foo]` and `set[Foo]` instead of `List[Foo]` and `Set[foo]`, as well as `collections.abc.Iterable` and `collections.abc.Mapping` as opposed to `typing.Iterable` and `typing.Mapping`.

* Starting python3.10 ( #638 ) , we will have support for `TypeVar` including `bounds` https://docs.python.org/3.10/library/typing.html#typing.TypeVar . This will enable us to remove syntax like `Union[SingleDataset, Dict[str, SingleComponentData]]` and replace it with `SingleDataset`, where `SingleDataset = Dict[ComponentTypeVar, SingleComponentData]` and `ComponentTypeVar = TypeVar['ComponentTypeVar', bounds=[ComponentType, str]]`
* Starting python3.10, `Union` is deprecated and replaced with the much simpler syntax `|`
