### ISSUE TITLE
[FEATURE] State Estimation Features

### ISSUE THREAD

**Issue by Welthulk** [PowerGridModel/power-grid-model#469]
I have read the manuals, but unfortunately I cannot find out which features are supported by the State Estimation. 
Questions:
Are subnets supported?
Are island networks supported?
How are couplings on busbars modeled?
Are phase-shifting transformers supported?
Can transformer taps be estimated?
How are parallel lines and transformers handled?

Thank you very much for your answer

**Comment by TonyXiang8787** [comment]
@nitbharambe  can you help with these questions?

**Comment by TonyXiang8787** [comment]
Hi @Welthulk,

Thank you for your question. Since this is a questions ticket instead of bug/issue report. Can you re-post the question in our discussion board? We can react there.

https://github.com/orgs/PowerGridModel/discussions

I close this issue here.
