### ISSUE TITLE
[FEATURE] *Add voltage controlled generator*

### ISSUE THREAD

**Issue by SanPen** [PowerGridModel/power-grid-model#49]
It would be nice to have a voltage controlled generator model, since it would allow the simulation of broader grid models.

The generator will be modeled as a PV (active power + Voltage module set point) bus in the calculation engine.

BR,
Santiago

**Comment by petersalemink95** [comment]
The focus of Power Grid Model will be on distribution systems. Therefore I am closing this issue.

**Comment by petersalemink95** [comment]
@SanPen a similar issue about this is re-opened: https://github.com/PowerGridModel/power-grid-model/issues/185
