### ISSUE TITLE
[FEATURE] Check for necessary condition for observability

### ISSUE THREAD

**Issue by mgovers** [PowerGridModel/power-grid-model#508]
# Describe the feature request

Add a check that implements a necessary condition for observability listed in the [state estimation documentation](https://power-grid-model.readthedocs.io/en/stable/user_manual/calculations.html#state-estimation).

# Rationale

This is a first step towards #84 that implements the design + a simple check.

# Out of scope

Sufficient condition for observability in state estimation. The necessary and sufficient condition for observability is covered in #84 . Instead, as mentioned in #rationale , this is a first step that is already able to design and implement an initial check, which can then be extended on in #84

# Design

* [x] Create a separate header and/or class with checks for observability.
* [x] Create a new `NotObservableError`
* [x] When running any state estimation solver
  * [x] First run the observability checks.
  * [x] If the observability check fails, raise a `NotObservableError`
* [x] update state estimation documentation on the new check

# Mathematical logic of necessary condition

Here we describe the necessary conditions of observability. They are not sufficient conditions. Therefore, even if the dataset passes the check, it can still be unobservable.

## Count of measurements

Criteria of count of measurement

* A bus voltage is either not measured, magnitude measured, or phasor (magnitude + angle) measured.
  * We define `n_voltage_sensor = n_voltage_magnitude_sensor + n_voltage_phasor_sensor`
* In a graph, parallel edges (branches) connecting the same two nodes are merged to one. If there is one power sensor at from/to side of one of the parallel branches, it counts as one power measurement for this edge. Multiple sensors also count as one.
  * We define `n_branch_sensor` as the number of independent (as above) branch measurements.
* A bus injection is measured and counted as one power measurement, if one of the following is true. This logic is already built in the `MeasuredValues` class.
  * There is a node injection sensor directly
  * There is no connected appliance (load_gen, source). This is called zero injection.
  * There is at least one power sensor per connected appliance (load_gen, source).
  * We define `n_injection_sensor` using the criteria above.
* We define `n_power_sensor = n_branch_sensor + n_injection_sensor`.

## Necessary conditions

We show the order of necessary conditions in italic *check* statement as below. We check the conditions one by one, if one condition fails, we throw `NotObservableError` immediately.
* *check* `n_voltage_sensor >= 1`
* If `n_voltage_phasor_sensor == 0`
  * *check* `n_power_sensor >= n_bus -1`
* If `n_voltage_phasor_sensor > 0`
  * *check* `n_power_sensor + n_voltage_phasor_sensor >= n_bus`

# [Optional] Partial sufficient conditions with graph search

The following logic will not provide additional information as necessary conditions of the check. It can however provide a sufficient condition if certain criteria are met. In those special cases, we can guarantee the observability.

We suggest doing this in a separate PR if you want to work on this. Or we wait until a mathematical logic which provides a full sufficient condition.

* Build an un-directed graph (or directed graph with double edges for both direction) with vertices and edges. Parralel edges should be merged into one. Disable all edge by default.
  * Loop all edges
    * If an edge is measured (branch power sensor), enable the edge.
  * Loop all vertices
    * If a vertex is measured (bus injection power sensor)
      * If all connecting edges are already enabled, skip to next iteration.
      * Enable an arbitrary connecting edge which is disabled at this moment.
  * Initialize vertex status array as unreachable for all vertices.
  * If `n_voltage_phasor_sensor == 0`
    * Pick up one vertex with voltage sensor, perform depth first search (DFS) on enabled edges.
      * Mark the reached vertices as reachable (including the origin vertex)
  * If `n_voltage_phasor_sensor > 0`
    * Loop all vertices with voltage phasor sensor
      * If the vertex is already marked as reachable, continue to next iteration of loop.
      * Perform DFS from one vertex with voltage phasor sensor on enabled edges.
      * Mark all reached vertices as reachable (including the origin vertex)
    * **If all vertices are marked as reachable, we issue a sufficient condition check result.**
      * In this case, when later a `SparseMatrixError` is thrown, we do not put additional message saying "the system might be not observable". Because we know it is observable.
    * **Otherwise the we do not know if there is sufficient condition. Quit the function with undetermined.**

**Comment by mgovers** [comment]
> TBD: throw SparseMatrixError vs creating a new NotObservableError

@TonyXiang8787 do you have any thoughts on this?

**Comment by TonyXiang8787** [comment]
> > TBD: throw SparseMatrixError vs creating a new NotObservableError
> 
> @TonyXiang8787 do you have any thoughts on this?
> 
> AFAICT, they are two separate things and it should be a new `NotObservableError`.
> 
> Rationale:
> 
> * A non-sufficiently filled Ybus or other calculation parameters may still cause `SparseMatrixError`s. E.g.: Powerflow calculations may throw them as well.
> * Not all unobservable cases result in sparse matrix errors

If it fails the necessary condition check, it should throw `NotObservableError`. The places where `SparseMatrixError` is thrown, we keep them as is.

**Comment by mgovers** [comment]
> If all connecting edges are already enabled, quit the function. (undetermined situation)

so this is the case where Marc's work will provide a necessary and sufficient condition, right?

**Comment by TonyXiang8787** [comment]
> > If all connecting edges are already enabled, quit the function. (undetermined situation)
> 
> so this is the case where Marc's work will provide a necessary and sufficient condition, right?

That's one, the other one is when graph has cycles (with enabled edges).

**Comment by mgovers** [comment]
I'm thinking whether we can approach this in a 2-phase way (with incremental improvements).

The main body of this PR can be implemented with just this simple check without any graph search required:

![image](https://github.com/PowerGridModel/power-grid-model/assets/15234327/0548460f-0a0c-4a4d-8d66-5ef24defee96)

and then after that's merged, a more complex check with the above logic can be implemented.

**Comment by TonyXiang8787** [comment]
@mgovers After some thinking, I concluded that the graph search will not provide additional information. If the first three condition pass, the graph search will either conclude that all vertices are reachable, which is a **sufficient condition**, or result in undermined quit. It will never issue a failure on check of reachable vertices. I will put that part check into an invalid section.

**Comment by mgovers** [comment]
Closed by #523
