### ISSUE TITLE
[FEATURE] Static library wrapper around main model + math solver for speeding up tests

### ISSUE THREAD

**Issue by mgovers** [PowerGridModel/power-grid-model#529]
Relates to https://github.com/PowerGridModel/power-grid-model/issues/486

A major factor in the compilation is the fact that all 3 test files of the main model + the validator + the benchmark need to recompile all templates individually. Making a static library wrapper would reduce this to only 1 compilation.

The way to do that is the following:

* [x] Add a separate library to the tests directory: `tests/cpp_test_wrappers/`
  * [x] Add a `CMakeLists.txt` to expose a `STATIC` library `cpp_test_wrappers`
  * [x] Add a header `tests/cpp_test_wrappers/include/cpp_test_wrappers/main_model_wrapper.hpp`
    * [x] declare class:
      ```cpp
      class MainModelWrapper {
        private:
          class Impl;

        public:
          // all public methods of MainModel

        private:
          std::unique_ptr<Impl> impl_;
      }
      ```
  * [x] Add a cpp file `tests/cpp_wrappers/src/main_model_wrapper.cpp`
    * [x] declare class impl:
        ```cpp
        class MainModelWrapper::Impl : public MainModel {
          public:
            using MainModel::MainModelImpl;
        };
        ```
    * [x] implement all public methods of MainModelWrapper by forwarding the call to `MainModel`
    * [x] Add all static checks from `test_main_model_static.cpp` to this file
* [x] Modify `test_main_model_*.cpp`, the `cpp_validation` tests and the benchmark to use this library instead of the static `MainModel`
* [x] Optionally: Create a separate test executable for `test_main_model_*` to speed up compilation for people who are developing things upstream and don't care about main model yet (already done )
* [ ] Optionally: do the same for the MathModel
  * [ ] Split the MathModel tests into separate files

**Comment by TonyXiang8787** [comment]
I wonder if we are creating static library anyway, why don't we just make `power_grid_model` core library itself a static library. We try to compile the header files in several compilation unit.

**Comment by mgovers** [comment]
I've been thinking about that as well. Let's discuss offline

**Comment by mgovers** [comment]
As discussed: we will solve this in a different way
