### ISSUE TITLE
[FEATURE] make tap_pos optional

### ISSUE THREAD

**Issue by petersalemink95** [PowerGridModel/power-grid-model#576]
For users that want to use the automatic tap changer power flow, it does not really matter what the original `tap_pos` is. They are just interested in the final `tap_pos`, found by the automatic tap algorithm. At this moment `tap_pos` is required, since it is necessary for the other algorithms.

We can make `tap_pos` optional, if we assign it the value of `tap_nom` when it is not given

Update:
- [ ] transformer
- [ ] three winding transformer
- [ ] documentation
- [ ] validation checks
- [ ] unit tests should be updated

NOTE: `tap_nom` is Optional. If `tap_nom` is not given, it will be set to 0 as a default. In this case `tap_pos` will still be set to the value of `tap_nom = 0`.

**Comment by mgovers** [comment]
current functionality clamps the tap position: https://github.com/PowerGridModel/power-grid-model/blob/09ee5a6e3a65d21cb2d0dbc8bc18b29ecc405c5f/power_grid_model_c/power_grid_model/include/power_grid_model/component/transformer.hpp#L145-L149 (and idem for 3w-transformer).

this existing behaviour may impact users. if we decide that existing functionality is good enough, documentation should be improved
