### ISSUE TITLE
[Feature] Retry logic in automatic tap outer loop

### ISSUE THREAD

**Issue by mgovers** [PowerGridModel/power-grid-model#580]
Originally posted in #557 as https://github.com/PowerGridModel/power-grid-model/pull/557#discussion_r1584309983

```
try 
  math_result = math_solver.power_flow(calculation_method=calculation_method) 
catch (SparseMatrixError, IterationDiverge) 
  Run run_pf_with_regulation_per_solver(math_solver=math_solver, calculation_method=linear),   discard return 
  math_result = math_solver.power_flow(calculation_method=calculation_method)
```

I added a Jira ticket for that because I have reason to believe that #549 should solve this because of the discard step: the initial state is actually set to the solution of the `linear` calculation.

That leaves me with even more reason that all the other fallback logic is also unnecessary and we can just remove `calculate_with_retry` and, instead, directly call `calculate_`

FYI: I removed `InvalidPFResult` from this example due to below comments

**Comment by TonyXiang8787** [comment]
We still need this logic, but without the check of voltage levels.

But we need to catch `SparseMatrixError` or `IterationDiverge`

**Comment by mgovers** [comment]
> We still need this logic, but without the check of voltage levels.
> 
> But we need to catch `SparseMatrixError` or `IterationDiverge`

also maybe in a different location (top-level instead of bottom-level) because then the entire optimizer runs on `linear` method and then using the user-specified calculation.

NOTE: this could mean that the optimum refinement logic mentioned in #557 does not work. let's discuss in-person. c.c. @Jerry-Jinfeng-Guo
