### ISSUE TITLE
[BUG] *No transformer_tap_regulator in configuration file.*

### ISSUE THREAD

**Issue by figueroa1395** [PowerGridModel/power-grid-model#646]
**Describe the bug**

The transformer_tap_regulator component is missing from the [dataset_definitions.json](https://github.com/PowerGridModel/power-grid-model/blob/main/code_generation/data/dataset_class_maps/dataset_definitions.json) configuration file.

**Comment by mgovers** [comment]
That's the underlying issue. The actual bug is that it is not showing up in the C API `dataset_definitions.h`
