### ISSUE TITLE
[FEATURE] State estimation with uncertainty in tap position

### ISSUE THREAD

**Issue by mgovers** [PowerGridModel/power-grid-model#659]
**Describe the feature request**

State estimation tries to optimize the unknowns in the grid so as to optimally match the sensor measurements. Currently, tap position is assumed to be a known constant in the grid. However, it turns out that the (known) tap position value is incorrect and/or outdated.

This feature request would optimize the tap positions across the estimated state as well.

as requested by @IrenaDk

**Comment by petersalemink95** [comment]
In the current form of PGM this would not be possible. Why? Each state estimation calculation would relate to one snapshot in time. If you would calculate the tap position in a state estimation calculation the tap setting might change from timestamp to timestamp, which in reality will not happen. To find proper tap settings you have to include the entire time series in your analysis.

Me and @TonyXiang8787 are involved in research on this topic. If something interesting for PGM would pop up we will open an issue. For now, I'm closing this issue
