### ISSUE TITLE
[FEATURE] Automatic adjustment of transformer tap changer

### ISSUE THREAD

**Issue by TonyXiang8787** [PowerGridModel/power-grid-model#74]
# Feature

- Add control logic for transformer tap changer.
- In power flow calculation, add an option to change the tap changer of transformer automatically.

# Considerations

- How to model tap changer controller? A separate class or inside transformer?
- How to implement it in the power flow solver?

**Comment by Jerry-Jinfeng-Guo** [comment]
For the tap changer, we implemented a ranking algorithm for transformers (with tap) in the following PRs:
- [STEP 1]
- https://github.com/PowerGridModel/power-grid-model/pull/545
- https://github.com/PowerGridModel/power-grid-model/pull/558
- [UNIT TEST]
